- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/notification/entity/Notification.java
- src/main/java/com/sharespace/sharespace_server/notification/repository/NotificationRepository.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
close #58 
branch : 58/Feat-알림-기능-기초
- Notification 도메인 관련 클래스 및 인터페이스 생성
- Entity 클래스
- Repository 인터페이스
- Controller 클래스
- Service 클래스
> Feat/58 알림 기능 기초

- src/main/java/com/sharespace/sharespace_server/global/exception/error/NotificationException.java
- src/main/java/com/sharespace/sharespace_server/global/utils/S3ImageUpload.java
- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/notification/dto/response/NotificationAllResponse.java
- src/main/java/com/sharespace/sharespace_server/notification/repository/NotificationRepository.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
close #71
branch : Feat/71 -Image-Upload-Download
- 단일 이미지 수정 로직 추가
- 각 메서드별 주석 추가
- 메서드명 수정
-
> 이미지 수정 및 주석 추가

- src/main/java/com/sharespace/sharespace_server/global/exception/error/ImageException.java
- src/main/java/com/sharespace/sharespace_server/global/utils/S3ImageUpload.java
close #71
branch : Feat/71-Image-Upload-Download
- 단일 이미지 수정 시 삭제 url 이미지 검증 로직 추가
- profile 최초 생성 시 이미지가 없기 때문에 최초 수정 시 이미지 삭제하는 url 이 null 값이 들어와 이를 해결하기 위해 조건문 추가
- 다중 이미지 업로드 시 이미지가 중복으로 S3에 올라가는 문제 해결
- 예외처리 CustomException으로 변경 및 예외 항목 추가
> #71 [CHORE]-이미지 중복 업로드 해결 및 이미지 검증 로직 추가

- src/main/java/com/sharespace/sharespace_server/note/controller/NoteController.java
- src/main/java/com/sharespace/sharespace_server/note/dto/NoteRequest.java
- src/main/java/com/sharespace/sharespace_server/note/service/NoteService.java
- src/main/java/com/sharespace/sharespace_server/place/controller/PlaceController.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
branch : Refactor/78 -Place-Note-refactor
1. Place
(1) Image 업로드 후 DB에 저장 시 String으로 변환하는 과정에서 잘못된 형태로 변경되는 로직 수정
(2) Place Service 내 주석 추가
2. Note
(1) Note Controller 및 Note Request 내 validation 적용
(2) User을 불러오는 로직 메서드로 분리 및 적용
(3) validation 사용으로 불필요한 코드 삭제
> #78 [REFACTOR]-Place And Note 리팩토링

- src/main/java/com/sharespace/sharespace_server/product/controller/ProductController.java
- src/main/java/com/sharespace/sharespace_server/product/dto/ProductRegisterRequest.java
- src/main/java/com/sharespace/sharespace_server/product/entity/Product.java
- src/main/java/com/sharespace/sharespace_server/product/service/ProductService.java
branch : Chore/82-Image-Service-적용
- Product 등록 시 S3에 Image 업로드 로직 추가
- Image 업로드 시 버킷 네이밍 내 product Id값이 들어가게 하기 위해 Product Entity에서 **Image_url null 값을 허용으로 변경**함
- Request 값 중 Image를 제외한 나머지를 먼저 DB에 저장 후 productId값을 가져와 이미지 저장 시 적용하도록 로직 작성
> #82 [FEAT]-Product 등록 시 Image 로직 추가

- src/main/java/com/sharespace/sharespace_server/product/controller/ProductController.java
- src/main/java/com/sharespace/sharespace_server/product/dto/ProductRegisterResponse.java
close #8
branch : Feat/ProductDomainDesign
- Product 등록 후 성공적으로 DB 저장 및 S3에 이미지 저장 모두 성공적으로 등록 시 Response로 productId를 보내줌
- Place 선택 시 productId값을 가지고 카테고리에 맞는 장소 리스트를 반환하기 위한 작업
> #8 [FEAT]-Product 등록 시 Response로 productId 값을 넘겨주는 로직 추가

- src/main/java/com/sharespace/sharespace_server/product/service/ProductService.java
close #8
branch : Feat/ProductDomainDesign
- Product Service 내 Response 추가
> #8 [FIX]-Product Service 내 Response 추가

- src/main/java/com/sharespace/sharespace_server/matching/controller/MatchingController.java
- src/main/java/com/sharespace/sharespace_server/matching/dto/request/MatchingUploadImageRequest.java
- src/main/java/com/sharespace/sharespace_server/matching/dto/response/MatchingShowAllResponse.java
- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
#87
branch : Feat/87-Matching-API-개선
-  이미지 업로드 API 추가
- HTTP 메서드 (PUT -> PATCH) 변경
-  JavaDocs에 기반한 코드 주석 추가
> Matching API 기능 추가 및 개선

- build.gradle
- data.sql
- src/main/java/com/sharespace/sharespace_server/global/config/SecurityConfig.java
- src/main/java/com/sharespace/sharespace_server/global/exception/error/JwtException.java
- src/main/java/com/sharespace/sharespace_server/global/filter/JwtAuthenticationFilter.java
- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- src/main/java/com/sharespace/sharespace_server/global/utils/RequestParser.java
- src/main/java/com/sharespace/sharespace_server/jwt/domain/Jwt.java
- src/main/java/com/sharespace/sharespace_server/jwt/domain/JwtProvider.java
- src/main/java/com/sharespace/sharespace_server/jwt/entity/Token.java
- src/main/java/com/sharespace/sharespace_server/jwt/repository/TokenJpaRepository.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/JwtService.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/TokenBlacklistService.java
- src/main/java/com/sharespace/sharespace_server/user/entity/User.java
- src/main/java/com/sharespace/sharespace_server/user/service/CustomUserDetailService.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- src/main/resources/application-dev.yml
close #89
branch : Feat/UserLogin
- Token table 및 entity 정의
- RefreshToken 생성 및 쿠키 저장 메소드
- Security를 활용한 로그인 필터 구현
- jwt 인증 필터 구현 및 whiteList, blackList 정의
- jwt 관련 customException 정의
> 유저 로그인 기능 추가

- build.gradle
- data.sql
- src/main/java/com/sharespace/sharespace_server/global/config/SecurityConfig.java
- src/main/java/com/sharespace/sharespace_server/global/exception/error/JwtException.java
- src/main/java/com/sharespace/sharespace_server/global/filter/JwtAuthenticationFilter.java
- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- src/main/java/com/sharespace/sharespace_server/global/utils/RequestParser.java
- src/main/java/com/sharespace/sharespace_server/jwt/domain/Jwt.java
- src/main/java/com/sharespace/sharespace_server/jwt/domain/JwtProvider.java
- src/main/java/com/sharespace/sharespace_server/jwt/entity/Token.java
- src/main/java/com/sharespace/sharespace_server/jwt/repository/TokenJpaRepository.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/JwtService.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/TokenBlacklistService.java
- src/main/java/com/sharespace/sharespace_server/place/dto/PlaceRequestedDetailResponse.java
- src/main/java/com/sharespace/sharespace_server/product/dto/ProductRequestedDetailResponse.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/dto/UserUpdateRequest.java
- src/main/java/com/sharespace/sharespace_server/user/entity/User.java
- src/main/java/com/sharespace/sharespace_server/user/service/CustomUserDetailService.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- src/main/resources/application-dev.yml
#82
branch : Chore/82-Image-Service-적용
- 매칭 상세 조회에서 Product와 Place의 이미지 정보를 String값으로 반환하는 것이 아닌 List<String>으로 변환하여 반환(Response) 되도록 수정
- User Controller 내 어노테이션 @ModelAttribute 로 변경
- UserUpdateRequest에서 Image 타입 MultipartFile로 변경 및 profile 사진을 변경하지 않을 수 있기 때문에 NULL 허용
- UserService 내 이미지 업로드 추가
> Chore/82 image service 적용

- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/dto/UserGetInfoResponse.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
close # 93
branch : Feat/UserGetInfo
- UserController에 API 호출 관련 메소드 추가
- UserService에 API 기능 관련 메소드 추가
- Response 형태에 맞는 dto 정의
> 유저 정보 불러오기 관련 API 추가

- src/main/java/com/sharespace/sharespace_server/matching/dto/MatchingAssembler.java
- src/main/java/com/sharespace/sharespace_server/matching/entity/Matching.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/product/entity/Product.java
close #87
branch : Refactor/87-Matching-리팩토링
- DDD와 OOP를 기반으로 SRP를 위반한 내용 개선
- `MatchingAssembler` 활용 (Entity의 내용을 `DTO`로 변환하는 클래스를 `Assembler`로 따로 뺌)
- `findUser` 메서드 추가
- 유효성 검증, 거리 계산 등의 로직은 도메인 클래스 내에서 해결하도록 수정한 내용을 반영
> Matching 리팩토링

- src/main/java/com/sharespace/sharespace_server/place/dto/PlacesResponse.java
- src/main/java/com/sharespace/sharespace_server/place/entity/Place.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
- src/main/java/com/sharespace/sharespace_server/user/entity/User.java
#78
branch : Refactor/78-Place-Note-refactor
- 장소 수정에서 Location 수정은 User 엔티티에서 수정될 수 있도록 변경
- 장소 수정에서 유저 정보를 제외한 나머지는 Place 엔티티에서 수정될 수 있도록 책임 분리
- PlaceResponse의 형태로 List 제작 과정을 PlaceResponse 클래스 내에서 처리되도록 책임 분리
- 클린 코드 및 메서드 분리 위의 항목 적용된 PlaceService 리팩토링
> PlaceService 

- src/main/java/com/sharespace/sharespace_server/global/config/SecurityConfig.java
- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- src/main/java/com/sharespace/sharespace_server/jwt/controller/TokenController.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/JwtService.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
close #97 
branch :Feat/UserLogout
- 로그인시에 쿠키에 refreshToken 저장 기능 추가
- accessToken 만료시 refreshToken을 통한 새 accessToken 발급 기능 추가
- 로그아웃시 cookie에 존재하는 refreshToken과 accessToken을 blackList에 추가하여 무효화
- 로그아웃시 DB에 존재하는 refreshToken 삭제 처리
> 유저 로그인/로그아웃

- src/main/java/com/sharespace/sharespace_server/global/enums/NotificationMessage.java
- src/main/java/com/sharespace/sharespace_server/matching/dto/request/MatchingUploadImageRequest.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/note/service/NoteService.java
- src/main/java/com/sharespace/sharespace_server/product/repository/ProductRepository.java
#98 
branch : Feat/98-알림-고도화-및-매칭-개선
- 쪽지 서비스 계층에 알림 서비스 주입
- `/matching` api 주 오류 중 하나인 `ProductRepository`의 `findAllByUserId` 메서드 롤백
- `matching` 테이블에 이미지 업로드시 발생했던 버그 수정
- `NotificationMessage` Enum에 새로운 필드 추가
> Feat/98 알림 고도화 및 매칭 개선

- src/main/java/com/sharespace/sharespace_server/global/utils/S3ImageUpload.java
close #103
branch : Refactor/103-Image-Class-리팩토링
- S3ImageUpload 클래스 메서드 분리 등 래픽토링 진행
> #103 image class 리팩토링

- src/main/java/com/sharespace/sharespace_server/global/exception/error/UserException.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
close #105
branch : Chore/105-이메일인증-내용수정
- UserService 내 회원가입 시 이메일 인증 절차에서 이메일 내용 수정
- 디자인 변경
- 이메일 인증 유효기간(시간) 추가
- 이메일 인증 안내 사항 추가
> #105 이메일인증 내용수정

- data.sql
- src/main/java/com/sharespace/sharespace_server/global/enums/NotificationMessage.java
- src/main/java/com/sharespace/sharespace_server/matching/controller/MatchingController.java
- src/main/java/com/sharespace/sharespace_server/matching/dto/MatchingAssembler.java
- src/main/java/com/sharespace/sharespace_server/matching/dto/response/MatchingShowRequestDetailResponse.java
- src/main/java/com/sharespace/sharespace_server/matching/entity/Matching.java
- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/notification/NotificationScheduler.java
- src/main/java/com/sharespace/sharespace_server/place/dto/PlaceRequestedDetailResponse.java
close #98 
branch: Feat/98-알림-고도화-및-매칭-개선
- data.sql 수정
- `Matching` 테이블에 `expiry_date` 컬럼 추가
- `Matching` Entity 클래스 수정
- `expiry_date` 컬럼 추가에 따른 엔티티 클래스에도 필드 추가, `@ManyToOne` FetchType을 Lazy로 변경
- `MatchingService`의 `/matching` API를 처리하는 서비스 계층의 메서드 (`showAll()`)에서 N+1 문제 해결
- Response 잘못 나가는 문제점이 존재해 DTO 필드명 Rename
- Matching Detail 조회할 때 `Place`의 `description`이 누락되었던 문제 해결
- `MatchingRepository`에 `Fetch Join` 사용하는 쿼리 메서드들 추가
- `NotificationScheduler` 클래스 추가
- 일정 주기마다 특정 조건을 만족하는 알림을 전송하기 위함
> 알림 고도화 및 매칭 개선

- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/notification/dto/response/NotificationAllResponse.java
- src/main/java/com/sharespace/sharespace_server/notification/dto/response/NotificationResponse.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
#108 
branch : `Chore/108-FE와-API-연결`
- GET `/notification` API 응답 데이터들에 대해 오타가 있어 수정
- API 엔드포인트 잘못되어있던 것 수정
- SSE로 Client에게 데이터 전송 시 객체로 넘겨주도록 수정 (DTO 사용하여 구현) -> `NotificationResponse`
> Notifcation 관련 리팩토링 및 DTO 추가

- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/JwtService.java
- 잘못 저장되고 있던 token 형태 수정
- 쿠키 내 토큰 쌓임 현상 해결
> #110 [Fix] - 쿠키 내 토큰 쌓임 현상 해결

- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- User login시 response에 userId 추가
> #110 [Feat] - User login시 response에 userId 추가

- src/main/java/com/sharespace/sharespace_server/note/controller/NoteController.java
- src/main/java/com/sharespace/sharespace_server/note/service/NoteService.java
- src/main/java/com/sharespace/sharespace_server/place/controller/PlaceController.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
close #78 
branch : Refactor/78-Place-Note-refactor
기존 직접 userId를 넣어주는 방식에서 로그인 후 HttpServletRequest로 토큰 정보 불러와 userId 가져오도록 수정
> HttpServletRequest로 토큰 정보 불러와 userId 가져오도록 수정

- src/main/java/com/sharespace/sharespace_server/global/config/SecurityConfig.java
- src/main/java/com/sharespace/sharespace_server/global/exception/error/UserException.java
- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- src/main/java/com/sharespace/sharespace_server/jwt/service/JwtService.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- 기존 body값으로 받아오던 userId 토큰에서 추출하도록 수정
- DB 내 token 갱신해주는 로직 계층구조 재확립
> 계층 구조 리팩토링 / 토큰 사용 적용

- src/main/java/com/sharespace/sharespace_server/user/dto/UserUpdateRequest.java
> #110 [Fix] - 기존 body값으로 받아오던 userId를 토큰에서 추출하도록 수정 미비된 사항 추가 수정

- src/main/java/com/sharespace/sharespace_server/user/dto/UserRegisterRequest.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- 회원가입 요청 body에 empty 및 blank message 수정
- JavaMailSender 호출 수정
> #110 [Fix] - 회원가입 요청 body에 empty 및 blank message 수정

- src/main/java/com/sharespace/sharespace_server/SharespaceServerApplication.java
- src/main/java/com/sharespace/sharespace_server/user/UserCleanupScheduler.java
- src/main/java/com/sharespace/sharespace_server/user/repository/UserRepository.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- 스케줄러를 통해 emailValidated가 false인 user들을 자정마다 삭제
> 이메일 미인증 유저들 탈퇴처리 기능 추가

- src/main/java/com/sharespace/sharespace_server/user/UserCleanupScheduler.java
> test용으로 잘못기입된 스케줄러 시간 재설정

- src/main/java/com/sharespace/sharespace_server/SharespaceServerApplication.java
- src/main/java/com/sharespace/sharespace_server/user/UserCleanupScheduler.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/dto/UserGetIdResponse.java
- src/main/java/com/sharespace/sharespace_server/user/repository/UserRepository.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
#108
branch : `Chore/108-FE와-API-연결`
- `userId` 가져오는 API 메서드 추가
> #108 [FEAT]-userId를 가져오는 API 추가 및 이전 커밋 복구

- src/main/java/com/sharespace/sharespace_server/matching/controller/MatchingController.java
- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/notification/repository/NotificationRepository.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
#108 
branch : `Chore/108-FE와-API-연결`
- 알림 조회 API에 페이지네이션을 적용하여, `page`와 `size`를 Query Parameter로 전달받아 데이터를 일부만 보여주도록 변경
- Status에 따라 필터링하여 보여주는 API 추가
> 알림 조회 API에 페이지네이션 적용 및 Matching 필터링 API 추가

- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
close #127 
branch :  Fix/127-Note-오류-해결  
매칭테이블에서 하나의 상품 또는 장소에 대해 여러개의의 장소 또는 물품이 들어올 수 있어 다중값을 받아 올 수 있도록 수정
> #127 [FIX]-Note 전송 대상 API 다중 값 처리 오류 해결

- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- 로그아웃시에도 SSE 연결을 해제하도록 설정
- SSE 연결을 종료할 때 emitter.complete()를 호출하여 연결 종료를 명시
#108 
branch : `Chore/108-FE와-API-연결`
- 로그아웃시 SSE 연결을 해제하는 것을 명시
- Sse 연결 종료시 `emitter.complete()` 동작 추가
> [FIX]-API 무한 Pending 문제 해결

- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- 로그인시 잘못된 비밀번호를 입력할 때 error 타입 message/status 형태에 맞게 수정
> 로그인시 잘못된 비밀번호를 입력할 때 error 타입 수정

- src/main/java/com/sharespace/sharespace_server/place/controller/PlaceController.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
close #78 
branch :  Refactor/78-Place-Note-refactor
- UserId Controller 단에서 HttpServletRequest로 토큰 정보 불러와 가져오도록 수정
- 관련 주석 추가
> #78 UserId 토큰에서 가져오도록 수정

- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
UserController단 userId를 추출 방식 수정
- UserController단에서 userId를 추출해올때 정적메소드 import 방식에서 클래스 호출 방식으로 수정하여 객체지향성, 유지보수성, 가독성 등의 측면 개선
> UserController단 userId를 추출 방식 수정

- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- 기능 및 메소드별 주석 추가 및 미사용 파라미터 및 import문 삭제
> 기능 및 메소드별 주석 추가 및 미사용 파라미터 및 import문 삭제

- src/main/java/com/sharespace/sharespace_server/note/controller/NoteController.java
- src/main/java/com/sharespace/sharespace_server/note/service/NoteService.java
close #78
branch :  Refactor/78-Place-Note-refactor
- 쪽지 코드 주석 추가
- NoteService 코드리팩토링
> #78 Refactor Note Refactor

- src/main/java/com/sharespace/sharespace_server/global/enums/Category.java
- src/main/java/com/sharespace/sharespace_server/place/controller/PlaceController.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
close #139
branch :  Chore/139-Place-API-수정
- 물품에 맡는 장소 리스트 조회에서 RequestParam 값을 productId가 아닌 matchingId로 변경
- 변경된 코드에 따라 불필요 코드 제거
- 주석 변경
> #139 Place API 일부 수정

- src/main/java/com/sharespace/sharespace_server/product/dto/ProductRegisterResponse.java
- src/main/java/com/sharespace/sharespace_server/product/service/ProductService.java
#143
- Product 등록 시 Response 반환값 중 productId 제거
> #143 Product Response 변경

- build.gradle
- src/main/java/com/sharespace/sharespace_server/alarm/controller/AlarmController.java
- src/main/java/com/sharespace/sharespace_server/alarm/dto/AlarmDto.java
- src/main/java/com/sharespace/sharespace_server/alarm/entity/Alarm.java
- src/main/java/com/sharespace/sharespace_server/alarm/repository/AlarmRepository.java
- src/main/java/com/sharespace/sharespace_server/alarm/service/AlarmService.java
- src/main/java/com/sharespace/sharespace_server/contact/controller/ContactController.java
- src/main/java/com/sharespace/sharespace_server/global/annotation/CheckPermission.java
- src/main/java/com/sharespace/sharespace_server/global/aop/PermissionAspect.java
- src/main/java/com/sharespace/sharespace_server/global/config/AopConfig.java
- src/main/java/com/sharespace/sharespace_server/global/utils/RequestParser.java
- src/main/java/com/sharespace/sharespace_server/jwt/controller/TokenController.java
- src/main/java/com/sharespace/sharespace_server/matching/controller/MatchingController.java
- src/main/java/com/sharespace/sharespace_server/matching/controller/MatchingHistoryController.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/note/controller/NoteController.java
- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/place/controller/PlaceController.java
- src/main/java/com/sharespace/sharespace_server/product/controller/ProductController.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
close #141
branch : `Fix/141-API-문제-해결`
- Spring AOP 설정 및 관련 클래스 추가
- 각 컨트롤러 메서드에 `@CheckPermission` 어노테이션 적용
> 권한 확인에 Spring AOP 적용

- src/main/java/com/sharespace/sharespace_server/global/exception/error/ImageException.java
- src/main/java/com/sharespace/sharespace_server/global/exception/error/NoteException.java
- src/main/java/com/sharespace/sharespace_server/global/exception/error/PlaceException.java
- src/main/java/com/sharespace/sharespace_server/global/utils/S3ImageUpload.java
- src/main/java/com/sharespace/sharespace_server/note/service/NoteService.java
- src/main/java/com/sharespace/sharespace_server/place/repository/PlaceRepository.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
- src/main/resources/application.yml
#143
- APPLICATION.yml 파일 release -> dev 로 수정
- NoteService 내 쪽지 대상자 조회 메서드 내 대상자가 존재하지 않을 경우 예외처리로 처리하지만 빈값을 보내도록 예외처리 제거
- S3Image 관리 클래스 리팩토링 및 다중 삭제 기능 지원 메서드 사용
- PlaceService에서 물품에 맞는 장소 리스트 조회 필터를 카테고리 뿐만 아니라 최대 보관일수도 필터를 거쳐 조회할 수 있도록 수정
- Exception Status Code 각 상황에 맞는 code로 변경 및 적용
> API 기능 수정 및 리팩토링

- src/main/java/com/sharespace/sharespace_server/matching/controller/MatchingController.java
- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/notification/NotificationScheduler.java
- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
close #141 
branch : `Fix/141-API-문제-해결`
- SSE 연결에서 userId를 PathParam으로 받던 방식에서 토큰에서 가져오는 방식으로 변경
> SSE 연결 방식 수정

- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
- src/main/java/com/sharespace/sharespace_server/product/entity/Product.java
- src/main/java/com/sharespace/sharespace_server/product/service/ProductService.java
#143 
branch :  Chore/143-API-수정
- Product Product 생성 관심사 분리. 정적 팩토리 메서드를 사용하여 물품 생성을 Product.class에서 처리하도록 수정
- 물품에 맞는 장소 조회에서 카테고리 적용 안되는 문제 해결
> Chore/143 api 수정

- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
close #141
branch : `Fix/141-API-문제-해결`
- MatchingService 계층에서 Status 기준으로 필터링하는 로직 추가했습니다.
> #141 [CHORE]-Host 물품조회시 미배정, 반려됨은 안 보이게 수정

- src/main/java/com/sharespace/sharespace_server/place/controller/PlaceController.java
- src/main/java/com/sharespace/sharespace_server/place/dto/PlaceEditResponse.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
#143
- 장소 수정 전 로그인 한 사용자가 등록힌 장소 디테일과 사용자가 등록한 주소를 반환하는 API 제작
> #143 [FEAT]-장소 수정 전 로그인 한 사용자가 등록한 장소 디테일 조회

- src/main/java/com/sharespace/sharespace_server/global/filter/JwtAuthenticationFilter.java
- src/main/java/com/sharespace/sharespace_server/jwt/controller/TokenController.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- 만료된 엑세스 토큰 reissue시 로그인 인증 오류 해결
- 엑세스 토큰이 만료되어 로그인 인증이 되지 않던 사항 관련 어노테이션 제거 및 jwt인증 필터 로직 수정
> #110 [Fix] - 만료된 엑세스 토큰 reissue시 로그인 인증 오류 해결

- src/main/java/com/sharespace/sharespace_server/global/config/MailConfig.java
- src/main/java/com/sharespace/sharespace_server/global/filter/JwtAuthenticationFilter.java
- src/main/java/com/sharespace/sharespace_server/user/controller/UserController.java
- src/main/java/com/sharespace/sharespace_server/user/service/UserService.java
- src/main/resources/application-dev.yml
- 빈 생성 미인지로 인한 javaMailSender yml 메일 설정의 config파일 생성 및 이관 작업
> javaMailSender 메일 설정 수정

- src/main/java/com/sharespace/sharespace_server/place/dto/PlacesResponse.java
- src/main/java/com/sharespace/sharespace_server/place/service/PlaceService.java
#143
- Place 조회 시 여러장의 사진의 경우 랜덤으로 한장의 사진만 반환되도록 수정
- Place 조회 시 사용자 거리 기준으로 반경 5Km 내 위치한 장소만 조회 가능하도록 수정
- Place 반환 시 거리를 기준으로 오름차순 정렬 (가까운 거리 순으로 보여짐)
> #143 PlaceResponse 수정

- src/main/java/com/sharespace/sharespace_server/note/repository/NoteRepository.java
- src/main/java/com/sharespace/sharespace_server/place/dto/request/PlaceRequest.java
- src/main/java/com/sharespace/sharespace_server/place/dto/request/PlaceUpdateRequest.java
- src/main/java/com/sharespace/sharespace_server/place/dto/response/PlaceDetailResponse.java
- src/main/java/com/sharespace/sharespace_server/place/dto/response/PlaceEditResponse.java
- src/main/java/com/sharespace/sharespace_server/place/dto/response/PlaceRequestedDetailResponse.java
- src/main/java/com/sharespace/sharespace_server/place/dto/response/PlacesResponse.java
> #143 [FEAT]-쪽지 발신일 기준으로 내림차순 정렬

- src/main/java/com/sharespace/sharespace_server/global/enums/NotificationMessage.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
- src/main/java/com/sharespace/sharespace_server/notification/controller/NotificationController.java
- src/main/java/com/sharespace/sharespace_server/notification/repository/NotificationRepository.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
close #151 
branch : `Test/151-Matching-테스트-및-버그-수정`
- SSE 연결시 Broken Pipe 에러 무시하도록 설정
- `Guest`가 물품 보관 확인시 알림이 전송되지 않던 문제 수정
> 알림 전체 삭제 API 및 알림 전송 누락 해결

- src/main/java/com/sharespace/sharespace_server/matching/repository/MatchingRepository.java
- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
#143
- 보관 대기중일 경우 요청을 취소 가능하지만, 안되는 현상 해결
- 물품 등록 현황 조회 시 보관 완료된 상태는 제외하고 반환하도록 쿼리문 수정
> #143 Matching API 코드 개선

- src/main/java/com/sharespace/sharespace_server/global/filter/LoginFilter.java
- 서로 다른 도메인 간의 쿠키 전송을 위한 samesite 설정 추가
> LoginFilter에 Samesite 설정 추가

- src/main/java/com/sharespace/sharespace_server/global/exception/handler/BaseExceptionHandler.java
- src/main/java/com/sharespace/sharespace_server/matching/entity/Matching.java
- src/main/java/com/sharespace/sharespace_server/notification/service/NotificationService.java
close #151
branch :
- 앞으로 `IOException` : broken pipe는 무시하도록 처리
- Matching을 cancel할 때 상태가 이미 `UNASSIGNED`면 업데이트하지 않도록 변경
> Broken Pipe 에러 무시 처리, Matching 상태 변경 로직 업데이트

- src/main/java/com/sharespace/sharespace_server/matching/service/MatchingService.java
close #173
branch : Feat/HostDashboard
- 서비스단 메소드 내 matching 테이블 expiryDate 비교 로직에 당일도 response에 추가되도록 수정
> #173 Host User의 Dashboard중 반납기한 당일인 항목 추가
